# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bigbot/cg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bigbot/cg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bigbot/cg/CMakeFiles /home/bigbot/cg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bigbot/cg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named visualization_headers

# Build rule for target.
visualization_headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visualization_headers
.PHONY : visualization_headers

# fast build rule for target.
visualization_headers/fast:
	$(MAKE) -f include/CMakeFiles/visualization_headers.dir/build.make include/CMakeFiles/visualization_headers.dir/build
.PHONY : visualization_headers/fast

#=============================================================================
# Target rules for targets named visualization

# Build rule for target.
visualization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visualization
.PHONY : visualization

# fast build rule for target.
visualization/fast:
	$(MAKE) -f src/CMakeFiles/visualization.dir/build.make src/CMakeFiles/visualization.dir/build
.PHONY : visualization/fast

#=============================================================================
# Target rules for targets named cg-test

# Build rule for target.
cg-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cg-test
.PHONY : cg-test

# fast build rule for target.
cg-test/fast:
	$(MAKE) -f tests/CMakeFiles/cg-test.dir/build.make tests/CMakeFiles/cg-test.dir/build
.PHONY : cg-test/fast

#=============================================================================
# Target rules for targets named cg_test_headers

# Build rule for target.
cg_test_headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cg_test_headers
.PHONY : cg_test_headers

# fast build rule for target.
cg_test_headers/fast:
	$(MAKE) -f tests/CMakeFiles/cg_test_headers.dir/build.make tests/CMakeFiles/cg_test_headers.dir/build
.PHONY : cg_test_headers/fast

#=============================================================================
# Target rules for targets named viewer-example

# Build rule for target.
viewer-example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viewer-example
.PHONY : viewer-example

# fast build rule for target.
viewer-example/fast:
	$(MAKE) -f examples/viewer/CMakeFiles/viewer-example.dir/build.make examples/viewer/CMakeFiles/viewer-example.dir/build
.PHONY : viewer-example/fast

#=============================================================================
# Target rules for targets named ccw_convex_contains_point

# Build rule for target.
ccw_convex_contains_point: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ccw_convex_contains_point
.PHONY : ccw_convex_contains_point

# fast build rule for target.
ccw_convex_contains_point/fast:
	$(MAKE) -f examples/operations/CMakeFiles/ccw_convex_contains_point.dir/build.make examples/operations/CMakeFiles/ccw_convex_contains_point.dir/build
.PHONY : ccw_convex_contains_point/fast

#=============================================================================
# Target rules for targets named contour_contains_point

# Build rule for target.
contour_contains_point: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 contour_contains_point
.PHONY : contour_contains_point

# fast build rule for target.
contour_contains_point/fast:
	$(MAKE) -f examples/operations/CMakeFiles/contour_contains_point.dir/build.make examples/operations/CMakeFiles/contour_contains_point.dir/build
.PHONY : contour_contains_point/fast

#=============================================================================
# Target rules for targets named first_problem

# Build rule for target.
first_problem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 first_problem
.PHONY : first_problem

# fast build rule for target.
first_problem/fast:
	$(MAKE) -f examples/operations/CMakeFiles/first_problem.dir/build.make examples/operations/CMakeFiles/first_problem.dir/build
.PHONY : first_problem/fast

#=============================================================================
# Target rules for targets named rectangle_intersects_segment

# Build rule for target.
rectangle_intersects_segment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rectangle_intersects_segment
.PHONY : rectangle_intersects_segment

# fast build rule for target.
rectangle_intersects_segment/fast:
	$(MAKE) -f examples/operations/CMakeFiles/rectangle_intersects_segment.dir/build.make examples/operations/CMakeFiles/rectangle_intersects_segment.dir/build
.PHONY : rectangle_intersects_segment/fast

#=============================================================================
# Target rules for targets named segments_intersect

# Build rule for target.
segments_intersect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 segments_intersect
.PHONY : segments_intersect

# fast build rule for target.
segments_intersect/fast:
	$(MAKE) -f examples/operations/CMakeFiles/segments_intersect.dir/build.make examples/operations/CMakeFiles/segments_intersect.dir/build
.PHONY : segments_intersect/fast

#=============================================================================
# Target rules for targets named triangle_contains_point

# Build rule for target.
triangle_contains_point: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangle_contains_point
.PHONY : triangle_contains_point

# fast build rule for target.
triangle_contains_point/fast:
	$(MAKE) -f examples/operations/CMakeFiles/triangle_contains_point.dir/build.make examples/operations/CMakeFiles/triangle_contains_point.dir/build
.PHONY : triangle_contains_point/fast

#=============================================================================
# Target rules for targets named triangle_intersects_segment

# Build rule for target.
triangle_intersects_segment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangle_intersects_segment
.PHONY : triangle_intersects_segment

# fast build rule for target.
triangle_intersects_segment/fast:
	$(MAKE) -f examples/operations/CMakeFiles/triangle_intersects_segment.dir/build.make examples/operations/CMakeFiles/triangle_intersects_segment.dir/build
.PHONY : triangle_intersects_segment/fast

#=============================================================================
# Target rules for targets named orientation_contour_ccw

# Build rule for target.
orientation_contour_ccw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orientation_contour_ccw
.PHONY : orientation_contour_ccw

# fast build rule for target.
orientation_contour_ccw/fast:
	$(MAKE) -f examples/orientation/CMakeFiles/orientation_contour_ccw.dir/build.make examples/orientation/CMakeFiles/orientation_contour_ccw.dir/build
.PHONY : orientation_contour_ccw/fast

#=============================================================================
# Target rules for targets named convex_hull

# Build rule for target.
convex_hull: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convex_hull
.PHONY : convex_hull

# fast build rule for target.
convex_hull/fast:
	$(MAKE) -f examples/convex_hull/CMakeFiles/convex_hull.dir/build.make examples/convex_hull/CMakeFiles/convex_hull.dir/build
.PHONY : convex_hull/fast

#=============================================================================
# Target rules for targets named dynamic_convex_hull

# Build rule for target.
dynamic_convex_hull: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dynamic_convex_hull
.PHONY : dynamic_convex_hull

# fast build rule for target.
dynamic_convex_hull/fast:
	$(MAKE) -f examples/convex_hull/CMakeFiles/dynamic_convex_hull.dir/build.make examples/convex_hull/CMakeFiles/dynamic_convex_hull.dir/build
.PHONY : dynamic_convex_hull/fast

#=============================================================================
# Target rules for targets named ccw_contour_convex

# Build rule for target.
ccw_contour_convex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ccw_contour_convex
.PHONY : ccw_contour_convex

# fast build rule for target.
ccw_contour_convex/fast:
	$(MAKE) -f examples/convex/CMakeFiles/ccw_contour_convex.dir/build.make examples/convex/CMakeFiles/ccw_contour_convex.dir/build
.PHONY : ccw_contour_convex/fast

#=============================================================================
# Target rules for targets named duglas_pecher

# Build rule for target.
duglas_pecher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 duglas_pecher
.PHONY : duglas_pecher

# fast build rule for target.
duglas_pecher/fast:
	$(MAKE) -f examples/duglas_pecher/CMakeFiles/duglas_pecher.dir/build.make examples/duglas_pecher/CMakeFiles/duglas_pecher.dir/build
.PHONY : duglas_pecher/fast

#=============================================================================
# Target rules for targets named new_task

# Build rule for target.
new_task: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 new_task
.PHONY : new_task

# fast build rule for target.
new_task/fast:
	$(MAKE) -f examples/new_task/CMakeFiles/new_task.dir/build.make examples/new_task/CMakeFiles/new_task.dir/build
.PHONY : new_task/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... visualization_headers"
	@echo "... visualization"
	@echo "... cg-test"
	@echo "... cg_test_headers"
	@echo "... viewer-example"
	@echo "... ccw_convex_contains_point"
	@echo "... contour_contains_point"
	@echo "... first_problem"
	@echo "... rectangle_intersects_segment"
	@echo "... segments_intersect"
	@echo "... triangle_contains_point"
	@echo "... triangle_intersects_segment"
	@echo "... orientation_contour_ccw"
	@echo "... convex_hull"
	@echo "... dynamic_convex_hull"
	@echo "... ccw_contour_convex"
	@echo "... duglas_pecher"
	@echo "... new_task"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

